# Generated by Django 3.1 on 2020-08-19 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('review', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('age', models.DateField()),
                ('signature', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('season', models.TextField(choices=[('Winter', 'Winter'), ('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn')])),
                ('day', models.TextField(choices=[('Day', 'Day'), ('Night', 'Night')])),
                ('sillage', models.TextField(choices=[('close to skin', 'close to skin'), ('arm length', 'arm length'), ('radiate 6ft', 'radiate 6ft'), ('fills the room', 'fills the room')])),
                ('longevity', models.TextField(choices=[('30 minutes to an hour', '30 minutes to an hour'), ('1 hour to 2 hours', '1 hour to 2 hours'), ('3 hours to 6 hours', '3 hours to 6 hours'), ('7 hours to 12 hours', '7 hours to 12 hours'), ('Longer than 12 hours', 'Longer than 12 hours')])),
                ('forwhom', models.TextField(choices=[('Females over 25', 'Females over 25'), ('Females under 25', 'Females under 25'), ('Male over 25', 'Male over 25'), ('Male under 25', 'Male under 25')])),
                ('price', models.IntegerField(max_length=10000)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='review.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'review')},
            },
        ),
    ]
